### PR TITLE
[#103][#117] Introduce optional "verbose" test failure reporting and increase test coverage

### PR DESCRIPTION
**Pull request by calebevans**
## Verbose Test Failure Reporting

This pull request introduces a new option in the firewatch CLI: `--verbose-test-failure-reporting` (and `--verbose-test-failure-reporting-ticket-limit`). The new option allows users to optionally report on every test failure found in job (up to the limit defined in `--verbose-test-failure-reporting-ticket-limit` which is 10 by default). 

When this functionality is enabled, it also changes the behavior of the duplicate bug search functionality by further specifying the specific test that has failed when searching. This same behavior is observed in the "past bugs" table in the issue description, so all past bugs in the table are relevant to that test name.

This was requested by the RHTAP team and may allow them to start using the tool in their OpenShift CI pipeline.

[*Example of a bug created using this functionality:*](https://issues.stage.redhat.com/browse/LPTOCPCI-868)

jira-ticket-example-verbose

## Test Coverage

Not much here, other than increased coverage. We are now at **72.89%** coverage. We were previously at **58.69%** coverage.

### CODE REVIEW

**Comment by calebevans** [comment]
@myakove I cannot see the tox failures and cannot acknowledge the sonarqube issues. Should we just move the tox execution to a GitHub action?

**Comment by myakove** [comment]
> @myakove I cannot see the tox failures and cannot acknowledge the sonarqube issues. Should we just move the tox execution to a GitHub action?

Sure, I will remove firewatch from the webhook configuration tomorrow.

**Comment by myakove** [comment]
@calebevans `tox` and `sonarqube` checks removed (you can ignore the failed ones), new PRs will not ave them.

**Comment by Simranpal** [comment]
> [_Example of a bug created using this functionality:_](https://issues.stage.redhat.com/browse/LPTOCPCI-868)
I cannot access the ticket, got access denied

**Comment by calebevans** [comment]
@Simranpal yeah that is in the stage environment, you'll have to set up some proxies. I'll ping you in slack with more info

**Pull request merged**
