### PR TITLE
[Issue #53] Change Commands and Arguments to Use a Hyphen Rather Than an Underscore

### PR DESCRIPTION
**Pull request by calebevans**
This PR will convert all the underscores to hyphens in the commands and arguments to make firewatch more user-friendly in the command line.

> NOTE:
> 
> This change will not affect firewatch in OpenShift CI yet. This is part of some maintence that needs to be done. Once the maintenance is done, I will switch the OpenShift CI from the `release-v1` branch back to the `main` branch.

### CODE REVIEW

**Review by dfrazzette — APPROVED** [review]
/lgtm

**Comment by myakove** [comment]
@calebevans this should be merged only after everyone have PRs in openshift-ci that handle it.

**Comment by calebevans** [comment]
@myakove I already wrote a PR in OpenShift CI that moves the ref to use the `release-v1` branch rather than `main` for this purpose. I have more changes coming that would also break that functionality anyway.

**Pull request merged**
