### PR TITLE
Added catalog-info.yaml file for backstage

### PR DESCRIPTION
**Pull request by rujutashinde**

### CODE REVIEW

**Comment by calebevans** [comment]
Hi @rujutashinde - thanks for getting this started 🙂 

Please let me know if there is anything I can help with. I noticed a pre-commit check failed, if you need to add configuration to that check for this to get through, please feel free to.

When you are ready for review, tag me in a comment or reach out on Slack!

**Comment by rujutashinde** [comment]
> Hi @rujutashinde - thanks for getting this started 🙂
> 
> Please let me know if there is anything I can help with. I noticed a pre-commit check failed, if you need to add configuration to that check for this to get through, please feel free to.
> 
> When you are ready for review, tag me in a comment or reach out on Slack!

@calebevans , so i see the pre-commit hook failing for yaml. the issue is the format for the catalog file is  not following the regular yaml setup, is there a way to ignore this check? or skip this file from this check?

**Review by calebevans — APPROVED** [review]
/lgtm

**Pull request merged**
